---
- name: 'Enterprise Linux - Add InfluxData repository file'
  template:
    src: 'influxdata.repo.j2'
    dest: '/etc/yum.repos.d/influxdata.repo'
    force: 'yes'
    backup: 'yes'
  when: kapacitor_use_repo

- name: 'Enterprise Linux - Install Kapacitor via package'
  yum:
    name: 'kapacitor'
    state: 'present'
  notify: 'restart kapacitor'
  when: kapacitor_use_repo

- name: 'Enterprise Linux - Install Kapacitor via URL'
  yum:
    name: "{{ kapacitor_rpm_pkg_url }}"
    state: 'present'
  notify: 'restart kapacitor'
  when: not kapacitor_use_repo
