---
# Copyright 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: 'Create Kapacitor DSL directories'
  file:
    path:  "{{ item }}"
    state: 'directory'
    recurse: 'yes'
  with_items:
    - "{{ kapacitor_tick_script_dest_dir }}"
    - "{{ kapacitor_tick_template_dest_dir }}"
    - "{{ kapacitor_tick_var_dest_dir }}"
  tags: 'kapacitor-tick'

- name: 'Copy Kapacitor TICK script files'
  copy:
    src:  "{{ item }}"
    dest: "{{ kapacitor_tick_script_dest_dir }}"
  with_fileglob:
    - "{{ kapacitor_tick_script_dir }}/*.tick"
  tags: 'kapacitor-tick'

- name: 'Copy Kapacitor TICK template files'
  copy:
    src:  "{{ item }}"
    dest: "{{ kapacitor_tick_template_dest_dir }}"
  with_fileglob:
    - "{{ kapacitor_tick_template_dir }}/*.tick"
  tags: 'kapacitor-tick'

- name: 'Copy Kapacitor TICK var files'
  copy:
    src:  "{{ item }}"
    dest: "{{ kapacitor_tick_var_dest_dir }}"
  with_fileglob:
    - "{{ kapacitor_tick_var_dir }}/*.json"
  tags: 'kapacitor-tick'

- name: 'Define Kapacitor templates'
  shell: |
      kapacitor define-template {{ item.id }} \
          -type {{ item.type }} \
          -tick {{ item.tick }} \
  with_items: "{{ kapacitor_templates }}"
  when:
    - kapacitor_templates | length > 0
    - item.enabled
  tags: 'kapacitor-tick'

- name: 'Define Kapacitor tasks'
  shell: |
      kapacitor define {{ item.id }} \
          {%if item.type is defined %}-type {{ item.type }} \ {% endif %}
          {%if item.vars is defined %}-vars {{ item.vars }} \ {% endif %}
          {%if item.template is defined %}-template {{ item.template }} \ {% endif %}
          -dbrp {{ item.dbrp }}
  with_items: "{{ kapacitor_tasks }}"
  when:
    - kapacitor_tasks | length > 0
    - item.enabled
  tags: 'kapacitor-tick'

- name: 'Disable Kapacitor tasks'
  shell: |
      kapacitor disable {{ item.id }}
  when:
    - kapacitor_tasks | length > 0
    - not item.enabled
  with_items: "{{ kapacitor_tasks }}"
  tags:
    - 'kapacitor-tick'
    - 'kapacitor-task'

# Enable tasks only once
- name: 'Enable Kapacitor tasks'
  shell: |
      kapacitor enable {{ item.id }}
  when:
    - kapacitor_tasks | length > 0
    - item.enabled
  with_items: "{{ kapacitor_tasks }}"
  run_once: true
  tags:
    - 'kapacitor-tick'
    - 'kapacitor-task'
